### PR TITLE
timeseries write missing/screening example

### PR DESCRIPTION
**Pull request by msweier**

### CODE REVIEW

**Comment by Enovotny** [comment]
can you update the number to 04 it seems like the repo you have didn't have the 03_data analysis example in it.  That is fine just update your name to 04.  Also can you test and apply the new change the Mike has where the value can be null.

**Comment by msweier** [comment]
> can you update the number to 04 it seems like the repo you have didn't have the 03_data analysis example in it. That is fine just update your name to 04. Also can you test and apply the new change that Mike has where the value can be null.

Yep I can change the name to 04. I tested it (see https://github.com/USACE/cwms-data-api/pull/913#issuecomment-2429371051). We can use None or 'null' too, but you still need the quality code. At this point I think it may be easiest to keep using the -Max.Float value to keep it numeric. pd.NA did not work.

**Comment by Enovotny** [comment]
> > can you update the number to 04 it seems like the repo you have didn't have the 03_data analysis example in it. That is fine just update your name to 04. Also can you test and apply the new change that Mike has where the value can be null.
> 
> Yep I can change the name to 04. I tested it (see [USACE/cwms-data-api#913 (comment)](https://github.com/USACE/cwms-data-api/pull/913#issuecomment-2429371051)). We can use None or 'null' too, but you still need the quality code. At this point I think it may be easiest to keep using the -Max.Float value to keep it numeric. pd.NA did not work.

that makes sense.  Let's keep it and then we can update the pd_to_json to accept the pd.NA and convert it correctly.

**Review by Enovotny — APPROVED** [review]

**Comment by Enovotny** [comment]
go ahead and merge this when you are ready.

**Pull request merged**
